# Generated by Django 3.0.7 on 2020-06-12 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_auto_20200612_0250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='filter',
            new_name='purifier',
        ),
    ]
